


export default {
    id: "dark-vscode",
    label: "VS Code Dark+",
    appearance: "dark",
    order: -90,
    isBuiltin: true,
    tokens: {
        "--app-theme-bg": "#202224",
        "--app-theme-surface": "#2a2d30",
        "--app-theme-surface-elevated": "#31353a",
        "--app-theme-sidebar-bg": "#26292d",
        "--app-theme-panel-muted": "#23262a",
        "--app-theme-border": "#3c3c3c",
        "--app-theme-border-strong": "#4d4d4d",
        "--app-theme-text-primary": "#cccccc",
        "--app-theme-text-secondary": "#b8b8b8",
        "--app-theme-text-tertiary": "#9b9b9b",
        "--app-theme-hover-background": "#32363b",
        "--app-theme-active-background": "#3c4148",
        "--app-theme-accent": "#3794ff",
        "--app-theme-accent-soft": "rgba(55, 148, 255, 0.18)",
        "--app-theme-control-bg": "#3f4348",
        "--app-theme-control-bg-hover": "#484d53",
        "--app-theme-control-border": "#45494e",
        "--app-theme-control-border-hover": "#5a5d61",
        "--app-theme-control-focus": "#3794ff",
        "--app-theme-mask": "rgba(0, 0, 0, 0.5)",
        "--app-theme-tooltip-bg": "#252526",
        "--app-theme-tooltip-border": "#454545",
        "--app-theme-tooltip-text": "#cccccc",
        "--app-theme-dialog-header-bg": "#252526",
        "--app-theme-dialog-footer-border": "#3c3c3c",
        "--app-theme-shadow": "0 18px 36px rgba(0, 0, 0, 0.45)",
        "--app-theme-button-bg": "#3c3c3c",
        "--app-theme-button-text": "#cccccc",
        "--app-theme-button-border": "#3c3c3c",
        "--app-theme-button-hover-bg": "#45494e",
        "--app-theme-button-hover-text": "#ffffff",
        "--app-theme-button-hover-border": "#5a5d61",
        "--app-theme-button-primary-bg": "#0e639c",
        "--app-theme-button-primary-text": "#ffffff",
        "--app-theme-button-primary-border": "#1177bb",
        "--app-theme-button-primary-hover-bg": "#1177bb",
        "--app-theme-button-primary-hover-border": "#1485d1",
        "--app-theme-titlebar-bg": "#252526",
        "--app-theme-titlebar-tab-bg": "#252526",
        "--app-theme-titlebar-tab-active-bg": "#1e1e1e",
        "--app-theme-titlebar-tab-border": "#3c3c3c",
        "--app-theme-titlebar-tab-text": "#969696",
        "--app-theme-titlebar-tab-active-text": "#ffffff",
        "--app-theme-titlebar-tab-hover-bg": "#2d2d30",
        "--app-theme-titlebar-tab-accent": "#3794ff",
        "--app-theme-tabs-bg": "#24272b",
        "--app-theme-tabs-surface": "#2a2d30",
        "--app-theme-tabs-muted": "#2f3338",
        "--app-theme-tabs-border": "#3c3c3c",
        "--app-theme-tabs-text": "#b0b0b0",
        "--app-theme-tabs-active-text": "#ffffff",
        "--app-theme-tabs-close-hover-bg": "rgba(255, 255, 255, 0.08)",
        "--app-theme-tabs-close-hover-text": "#ffffff",
        "--app-theme-statusbar-bg": "#007acc",
        "--app-theme-statusbar-border": "rgba(0, 0, 0, 0.28)",
        "--app-theme-statusbar-text": "#ffffff",
        "--app-theme-statusbar-hover-bg": "rgba(255, 255, 255, 0.12)",
        "--app-theme-statusbar-hover-text": "#ffffff",
        "--app-theme-statusbar-warning": "#ffcc00",
        "--app-theme-workbench-bg": "#202224",
        "--app-theme-workbench-panel-bg": "#2a2d30",
        "--app-theme-success": "#57ab5a",
        "--app-theme-success-soft": "rgba(87, 171, 90, 0.14)",
        "--app-theme-danger": "#f85149",
        "--app-theme-danger-soft": "rgba(248, 81, 73, 0.14)",
        "--app-theme-service-badge": "#57ab5a",
        "--app-theme-service-badge-border": "#57ab5a",
        "--app-theme-scrollbar-track": "rgba(255, 255, 255, 0.04)",
        "--app-theme-scrollbar-thumb-hover": "rgba(144, 147, 153, 0.5)",
        "--app-theme-splitter": "#3c3c3c",
        "--app-theme-splitter-hover": "#5a5d61",
        "--app-theme-splitter-text": "#ffffff",
        "--app-theme-window-close-hover-bg": "rgba(232, 17, 35, 0.9)",
        "--app-theme-window-close-hover-text": "#ffffff",
        "--app-theme-terminal-bg": "#1c2128",
        "--app-theme-terminal-fg": "#adbac7",
        "--app-theme-terminal-cursor": "#539bf5",
        "--app-theme-terminal-selection": "rgba(83, 155, 245, 0.24)",
        "--app-theme-editor-error-marker": "#ff7b72",
    },
}