export default {
    id: "light-default",
    label: "Light Default",
    appearance: "light",
    order: -100,
    isBuiltin: true,
    tokens: {
        "--app-theme-bg": "#f6f8fa",
        "--app-theme-surface": "#ffffff",
        "--app-theme-surface-elevated": "#f6f8fa",
        "--app-theme-sidebar-bg": "#f6f8fa",
        "--app-theme-panel-muted": "#f3f4f6",
        "--app-theme-border": "#d0d7de",
        "--app-theme-border-strong": "#afb8c1",
        "--app-theme-text-primary": "#24292f",
        "--app-theme-text-secondary": "#57606a",
        "--app-theme-text-tertiary": "#6e7781",
        "--app-theme-hover-background": "rgba(208, 215, 222, 0.32)",
        "--app-theme-active-background": "rgba(9, 105, 218, 0.12)",
        "--app-theme-accent": "#0969da",
        "--app-theme-accent-soft": "rgba(9, 105, 218, 0.14)",
        "--app-theme-control-bg": "#ffffff",
        "--app-theme-control-bg-hover": "#f6f8fa",
        "--app-theme-control-border": "#d0d7de",
        "--app-theme-control-border-hover": "#afb8c1",
        "--app-theme-control-focus": "#0969da",
        "--app-theme-mask": "rgba(27, 31, 36, 0.38)",
        "--app-theme-tooltip-bg": "#ffffff",
        "--app-theme-tooltip-border": "#d0d7de",
        "--app-theme-tooltip-text": "#24292f",
        "--app-theme-dialog-header-bg": "#f6f8fa",
        "--app-theme-dialog-footer-border": "#d0d7de",
        "--app-theme-shadow": "0 12px 28px rgba(31, 35, 40, 0.12)",
        "--app-theme-button-bg": "#f6f8fa",
        "--app-theme-button-text": "#24292f",
        "--app-theme-button-border": "#d0d7de",
        "--app-theme-button-hover-bg": "#f3f4f6",
        "--app-theme-button-hover-text": "#24292f",
        "--app-theme-button-hover-border": "#afb8c1",
        "--app-theme-button-primary-bg": "#1f883d",
        "--app-theme-button-primary-text": "#ffffff",
        "--app-theme-button-primary-border": "rgba(31, 35, 40, 0.15)",
        "--app-theme-button-primary-hover-bg": "#1a7f37",
        "--app-theme-button-primary-hover-border": "rgba(31, 35, 40, 0.15)",
        "--app-theme-titlebar-bg": "#f6f8fa",
        "--app-theme-titlebar-tab-bg": "#f6f8fa",
        "--app-theme-titlebar-tab-active-bg": "#ffffff",
        "--app-theme-titlebar-tab-border": "#d0d7de",
        "--app-theme-titlebar-tab-text": "#57606a",
        "--app-theme-titlebar-tab-active-text": "#24292f",
        "--app-theme-titlebar-tab-hover-bg": "#ffffff",
        "--app-theme-titlebar-tab-accent": "#fd8c73",
        "--app-theme-tabs-bg": "#f6f8fa",
        "--app-theme-tabs-surface": "#ffffff",
        "--app-theme-tabs-muted": "#f3f4f6",
        "--app-theme-tabs-border": "#d0d7de",
        "--app-theme-tabs-text": "#57606a",
        "--app-theme-tabs-active-text": "#24292f",
        "--app-theme-tabs-close-hover-bg": "rgba(9, 105, 218, 0.12)",
        "--app-theme-tabs-close-hover-text": "#0969da",
        "--app-theme-statusbar-bg": "#f6f8fa",
        "--app-theme-statusbar-border": "#d0d7de",
        "--app-theme-statusbar-text": "#57606a",
        "--app-theme-statusbar-hover-bg": "rgba(208, 215, 222, 0.32)",
        "--app-theme-statusbar-hover-text": "#24292f",
        "--app-theme-statusbar-warning": "#9a6700",
        "--app-theme-workbench-bg": "#ffffff",
        "--app-theme-workbench-panel-bg": "#f6f8fa",
        "--app-theme-success": "#1f883d",
        "--app-theme-success-soft": "rgba(31, 136, 61, 0.14)",
        "--app-theme-danger": "#cf222e",
        "--app-theme-danger-soft": "rgba(207, 34, 46, 0.14)",
        "--app-theme-service-badge": "#1f883d",
        "--app-theme-service-badge-border": "#1f883d",
        "--app-theme-scrollbar-track": "rgba(27, 31, 36, 0.08)",
        "--app-theme-scrollbar-thumb-hover": "rgba(87, 96, 106, 0.35)",
        "--app-theme-splitter": "#d0d7de",
        "--app-theme-splitter-hover": "#afb8c1",
        "--app-theme-splitter-text": "#ffffff",
        "--app-theme-window-close-hover-bg": "rgba(232, 17, 35, 0.9)",
        "--app-theme-window-close-hover-text": "#ffffff",
        "--app-theme-terminal-bg": "#f6f8fa",
        "--app-theme-terminal-fg": "#24292f",
        "--app-theme-terminal-cursor": "#0969da",
        "--app-theme-terminal-selection": "rgba(9, 105, 218, 0.18)",
        "--app-theme-editor-error-marker": "#b42318",
    },
}